version: '2.3'
services:
  opencv:
    image: pachyderm/opencv
    container_name: image finder
    ports:
      - "10000:8888" # jupyter
    environment:
      jupyter_base_url: /
      jupyter_pass: minh@2021
    volumes:
      - ./workspace:/workspace
      - ./run.sh:/run.sh
    user: root
    build:
      context: build
      dockerfile: Dockerfile
 
    #devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
    ipc: host
    restart: unless-stopped     # or "always"
